# hints={EOutOperation.GAME_START.value: '对局开始！',
#        EOutOperation.ENTER_PHASE.value: '进入{}阶段！'.format(Hint.emphasize_neutral('{}')),
#        EOutOperation.END_PHASE.value: '{}阶段结束！'.format(Hint.emphasize_neutral('{}')),
#        EOutOperation.END_GAME.value: '游戏结束！{}获得单局胜利！',
#        EOutOperation.END_MATCH.value: '对局结束！{}以{}:{}获得比赛胜利！',
#        EOutOperation.ENTER_TIME_POINT.value: '时点: {}'.format(Hint.emphasize_neutral('{}')),
#        EOutOperation.SP_DECIDED.value: '{}获得了先手！',
#        EOutOperation.SHOW_A_CARD.value: '轮到{}展示1张{}: ',
#        EOutOperation.CHOOSE_TARGET.value: '请您选择{}张：'.format(Hint.emphasize_neutral('{}')),
#        EOutOperation.ANNOUNCE_TARGET.value: '选择结果：{}',
#        EOutOperation.QUERY_FOR_REACT.value: '是否进行响应？',
#        EOutOperation.ANNOUNCE_DECISION.value: '选择结果: {}',
hints = {}
