from utils.constants import EOutOperation
from utils.hints import Hint

hints={EOutOperation.GAME_START.value: '对局开始！',
       EOutOperation.ENTER_PHASE.value: '进入{}阶段！'.format(Hint.emphasize_neutral('{}')),
       EOutOperation.END_PHASE.value: '{}阶段结束！'.format(Hint.emphasize_neutral('{}')),
       EOutOperation.END_GAME.value: '游戏结束！{}获得单局胜利！',
       EOutOperation.END_MATCH.value: '对局结束！{}以{}:{}获得比赛胜利！',
       EOutOperation.ENTER_TIME_POINT.value: '时点: {}'.format(Hint.emphasize_neutral('{}')),
       EOutOperation.SP_DECIDED.value: '{}获得了先手！',
       EOutOperation.SHOW_A_CARD.value: '轮到{}展示1张{}: ',
       EOutOperation.CHOOSE_TARGET.value: '请您选择{}张：'.format(Hint.emphasize_neutral('{}')),
       EOutOperation.ANNOUNCE_TARGET.value: '选择结果：{}',
       EOutOperation.QUERY_FOR_REACT.value: '是否进行响应？',
       EOutOperation.ANNOUNCE_DECISION.value: '选择结果: {}',
       '13': '对局开始！',
       '14': '对局开始！',
       '15': '对局开始！',
       '16': '对局开始！',
       '17': '对局开始！',
       '18': '对局开始！',
       '19': '对局开始！',
       '20': '对局开始！',
       '21': '对局开始！',
       '22': '对局开始！',
       '23': '对局开始！',
       '24': '对局开始！',
       '25': '对局开始！',
       '26': '对局开始！',
       '27': '对局开始！',
       '28': '对局开始！',
       '29': '对局开始！',
       '30': '对局开始！',
       '31': '对局开始！',
       '32': '对局开始！',
       '33': '对局开始！',
       '34': '对局开始！',
       '35': '对局开始！',
       '36': '对局开始！',
       '37': '对局开始！',
       '38': '对局开始！',
       '39': '对局开始！',
       '40': '对局开始！',
       '41': '对局开始！',
       '42': '对局开始！',
       '43': '对局开始！',
       '44': '对局开始！',
       '45': '对局开始！',
       '46': '对局开始！',
       '47': '对局开始！',
       '48': '对局开始！',
       '49': '对局开始！',
       '50': '对局开始！',
       '51': '对局开始！',
       '52': '对局开始！',
       '53': '对局开始！',
       '54': '对局开始！',
       '55': '对局开始！',
       '56': '对局开始！',
       '57': '对局开始！',
       '58': '对局开始！',
       '59': '对局开始！',
       '60': '对局开始！',
       '61': '对局开始！',
       '62': '对局开始！',
       '63': '对局开始！',
       '64': '对局开始！',
       '65': '对局开始！',
       '66': '对局开始！',
       '67': '对局开始！',
       }
